# @package _global_
variant:
  name: no_wait
  execution: online
  solver: CoSySolver
  exactness:
    complete_information: false
    method: heuristic
  cosy_repo:
    components:
      - casim.pipelines.problem_based_template.InstanceLoader
      - casim.pipelines.problem_based_template.OrdersProvider
      - casim.pipelines.subproblems.item_assingment.GreedyIA
      - casim.pipelines.subproblems.batching.FiFo
      - casim.pipelines.subproblems.picker_routing.TSPRouting
      - casim.pipelines.subproblems.scheduling.SPTScheduler
      - casim.pipelines.problem_based_template.ResultAggregationScheduling

engines:
  decision_engine:
    problems:
      OBRSP:
        solver:
          _target_: casim.pipelines.pipeline_runner.CoSySolver
          solution_ranker:
            _target_: casim.pipelines.solution_ranker.SolutionRanker
            objective: makespan
          repo: ${variant.cosy_repo}
        commitment_policy:
          _target_: casim.decision_engine.decision_engine.SchedulingCommitmentPolicy
          n_jobs: 1
    event_map:
      SequencingDone:
        _target_: hydra.utils.get_class
        path: casim.events.decision_events.SequencingDone
  simulation_engine:
    completion_mode: drain
    horizon_time: null
    problems:
      OBRSP:
        state_adapter:
          _target_: casim.simulation_engine.state_adapter.OrderWindowAdapter
        triggers: [casim.events.operational_events.OrderArrival, casim.events.operational_events.PickerIdle, casim.events.operational_events.FlushRemainingOrders]
        conditions:
          - _target_: casim.simulation_engine.simulation_engine.NbrPickersCondition
            threshold: 1
          - _target_: casim.simulation_engine.simulation_engine.NbrOrdersCondition
            threshold: 1
