name: WalkOrWait
problem_class: OBRSPW
objective: mean_order_completion_time
source:
  data_loader: WalkOrWaitDataLoader
layout:
  type: conventional
  objects:
    - name: LayoutParams
      features:
        - {name: n_blocks, value: 1}
        - {name: n_aisles}
        - {name: start_node}
        - {name: end_node}
        - {name: closest_node_to_start}
        - {name: min_aisle_position}
        - {name: max_aisle_position}
        - {name: distance_matrix}
        - {name: predecessor_matrix}
articles:
  type: standard
  objects:
    - name: Article
      features: [{name: article_id}]
orders:
  type: standard
  objects:
    - name: Order
      features: [{name: order_date}, {name: order_id}, {name: due_date}]
      objects:
        - name: OrderPosition
          features: [{name: amount}, {name: article_id}]
resources:
  type: human
  objects:
    - name: Resource
      features: [{name: speed}, {name: time_per_pick}]
      objects:
        - name: PickCart
          features: [{name: capacities}, {name: dimensions_type, value: [orders]}]
storage:
  type: dedicated
  objects:
    - name: StorageLocations
      features: [{name: amount}, {name: article_id}]
warehouse_info:
  type: online
  objects: []
