name: "grocery_retailer"
problem_type: ORSP

objective: tardiness
source:
  data_loader: GroceryRetailerLoader
  orders_path: "orders.csv"
  layout_path: "layout.csv"

layout:
  type: conventional
  objects:
    - name: LayoutParams
      features:
        - name: start_node
          value: [0, 0]
        - name: end_node
          value: [0, 0]
        - name: closest_node_to_start
          value: [0, 0]
        - name: min_aisle_position
          value: 0
        - name: max_aisle_position
          value: 10
        - name: n_pick_locations
          value: 50
        - name: dist_pick_locations
          value: 1.5
        - name: dist_bottom_to_pick_location
          value: 0
        - name: n_blocks
          value: 2
        - name: distance_matrix
        - name: predecessor_matrix

    - name: LayoutNetwork
      features:
        - name: graph
        - name: distance_matrix

articles:
  type: standard
  objects:
    - name: Article
      features:
        - name: article_id

orders:
  type: standard
  objects:
    - name: Order
      features:
        - name: order_date
        - name: due_date

      objects:
        - name: OrderPosition
          features:
            - name: article_id
            - name: amount

resources:
  type: human
  objects:
    - name: HumanPicker
      type: human
      features:
        - name: n_pickers
          value: 24
        - name: speed
          value: 2306
        - name: speed_follow_mode
          value: 1389
        - name: time_per_pick
          value: 19
        - name: tour_setup_time
          value: 215
        - name: aisle_congestion_rate
          value: 0.06

      objects:
        - name: PickCart
          type: manual
          features:
            - name: capacities
            - name: dimensions_type
              value: [items]

    - name: Cobot
      type: automated
      features:
        - name: distribution
          value: 0.5
        - name: time_per_pick
          value: 15.77

storage:
  type: dedicated
  objects:
    - name: StorageLocations
      features:
        - name: amount
        - name: article_id
