decision_engine:
  problems:
    ORSP:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}
      commitment_policy:
        _target_: casim.decision_engine.decision_engine.SchedulingCommitmentPolicy
        n_jobs: 1
    OBP:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}
      commitment_policy:
        _target_: casim.decision_engine.decision_engine.CommitAllPolicy

simulation_engine:
  problems:
    ORSP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.ORSPAdapter
      triggers: [ShiftStart, PickerArrival, PickerIdle]
      conditions:
        - _target_: casim.simulation_engine.conditions.NbrPickersCondition
          threshold: 1
        - _target_: casim.simulation_engine.conditions.NbrBatchesCondition
          threshold: 1
        - _target_: casim.simulation_engine.conditions.DockCapacityCondition
          threshold: 98

    OBP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.OBPAdapter
      triggers: [WMSRun]
      conditions: []