pipeline_runner:
  OBRSP:
    _target_: casim.pipelines.pipeline_runner.CoSyRunner
    endpoint: ResultAggregationScheduling
    problem_class: OBRSP

triggers:
  OrderArrival: OBRSP
  PickerIdle: OBRSP
  FlushRemainingOrders: OBRSP

conditions:
  OBRSP:
    - _target_: casim.state.conditions.NbrOrdersNbrPickersCondition
      order_window: 1
      picker_aval: 1

state_snapshot:
  OBRSP:
    _target_: casim.state.state_adapter.OBRSPAdapter

commitment_policy:
    _target_: casim.state.conditions.NbrOrdersNbrPickersCondition

fixed_algorithms:
  subproblem:
    item_assignment: GIA
    batching: ClarkAndWrightNN
    routing: NearestNeighbour
    scheduling: LPTScheduler
