decision_engine:
  problems:
    OBRP:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: distance
        repo: ${insertion_repo}
      commitment_policy:
        _target_: casim.decision_engine.commitment_policies.CommitAllPolicy
    OBRSPW:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}
      commitment_policy:
        _target_: casim.decision_engine.commitment_policies.CommitAllPolicy

simulation_engine:
  problems:
    OBRP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.ActiveTourAdapter
      triggers: [OrderArrival, NodeArrival, PickComplete]
      conditions:
        - _target_: casim.simulation_engine.conditions.NbrOrdersCondition
          threshold: 1
    OBRSPW:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.HennWaitingAdapter
      triggers: [PickerArrival, OrderArrival, OrderStreamClosed, PickerIdle, FlushRemainingOrders]
      conditions:
        - _target_: casim.simulation_engine.conditions.NbrPickersCondition
          threshold: 1
        - _target_: casim.simulation_engine.conditions.NbrOrdersCondition
          threshold: ${policy.wait_k}
          allow_when_done: true
