components:
  - casim.pipelines.problem_based_template.InstanceLoader
  - casim.pipelines.subproblems.item_assingment.GreedyIA
  - casim.pipelines.subproblems.batching.FiFo
  - casim.pipelines.subproblems.picker_routing.SShape
  - casim.pipelines.subproblems.picker_routing.Return
  - casim.pipelines.subproblems.picker_routing.LargestGap
  - casim.pipelines.subproblems.picker_routing.Midpoint
  - casim.pipelines.subproblems.picker_routing.NearestNeighbourhood
  - casim.pipelines.subproblems.scheduling.EDDScheduler
  - casim.pipelines.subproblems.scheduling.LPTScheduler
  - casim.pipelines.subproblems.scheduling.SPTScheduler
  - casim.pipelines.problem_based_template.PickListProvider
  - casim.pipelines.problem_based_template.ResultAggregationBatching
  - casim.pipelines.problem_based_template.ResultAggregationRouting
  - casim.pipelines.problem_based_template.ResultAggregationScheduling