# @package cosy_repo
components:
  - casim.pipelines.problem_based_template.InstanceLoader
  - casim.pipelines.problem_based_template.OrdersProvider
  - casim.pipelines.subproblems.item_assingment.GreedyIA
  - ${batching.component}
  - casim.pipelines.subproblems.picker_routing.SShape
  - casim.pipelines.problem_based_template.ResultAggregationRouting
