name: StochasticWaiting
problem_class: OBRSPW
objective: mean_order_completion_time
source:
  data_loader: StochasticWaitingDataLoader
layout:
  type: conventional
  objects:
    - name: LayoutParams
      features:
        - {name: n_blocks, value: 1}
        - {name: n_aisles, value: 8}
        - {name: n_pick_locations, value: 16}
        - {name: dist_aisle, value: 1.0}
        - {name: dist_pick_locations, value: 1.0}
        - {name: dist_bottom_to_pick_location, value: 1.0}
        - {name: dist_top_to_pick_location, value: 1.0}
        - {name: depot_location, value: front_left}
        - {name: dist_start, value: 1.0}
        - {name: dist_end, value: 1.0}
        - {name: start_node}
        - {name: end_node}
        - {name: closest_node_to_start}
        - {name: min_aisle_position}
        - {name: max_aisle_position}
        - {name: distance_matrix}
        - {name: predecessor_matrix}
articles:
  type: standard
  objects:
    - name: Article
      features: [{name: article_id}]
orders:
  type: standard
  objects:
    - name: Order
      features: [{name: order_date}, {name: order_id}, {name: order_lines_per_order, value: 1}]
      objects:
        - name: OrderPosition
          features: [{name: amount, value: 1}, {name: article_id}]
resources:
  type: human
  objects:
    - name: Resource
      features: [{name: speed}, {name: time_per_pick}]
      objects:
        - name: PickCart
          features: [{name: capacities, value: [1]}, {name: dimensions_type, value: [orders]}, {name: n_boxes, value: 4}, {name: box_can_mix_orders, value: false}]
storage:
  type: dedicated
  objects:
    - name: StorageLocations
      features: [{name: amount}, {name: article_id}]
warehouse_info:
  type: online
information:
  type: process_information
  objects:
    - name: incoming_orders
      features:
        - {name: type, value: exponential_single_line_uniform_location_order_stream}
        - {name: mean_interarrival_time_s, value: 28.8}
