components:
  - casim.pipelines.problem_based_template.InstanceLoader
  - casim.pipelines.problem_based_template.OrdersProvider
  - casim.pipelines.subproblems.item_assingment.GreedyIA
  - casim.pipelines.subproblems.admission.RemainingRouteAdmissionNode
  - casim.pipelines.problem_based_template.AdmittedTourBatch
  - casim.pipelines.subproblems.picker_routing.ReroutableSShape
  - casim.pipelines.problem_based_template.ResultAggregationRouting
