decision_engine:
  problems:
    ORSP:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}
    OBP:
      solver:
        _target_: casim.pipelines.pipeline_runner.CoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}

    RORSP:
      solver:
        _target_: casim.pipelines.pipeline_runner.OnlineCoSySolver
        solution_ranker:
          _target_: casim.pipelines.solution_ranker.SolutionRanker
          objective: ${data_card.objective}
        repo: ${cosy_repo}
  event_map:
    SequencingDone:
      _target_: hydra.utils.get_class
      path: casim.events.decision_events.SequencingDone

simulation_engine:
  completion_mode: horizon
  horizon_time: ${simulation.horizon_time}
  problems:
    ORSP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.ORSPAdapter
      triggers: [casim.events.operational_events.ShiftStart]
      conditions:
        - _target_: casim.simulation_engine.simulation_engine.NbrPickersCondition
          threshold: 1
        - _target_: casim.simulation_engine.simulation_engine.NbrBatchesCondition
          threshold: 1
        - _target_: casim.simulation_engine.simulation_engine.BreakCondition

    OBP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.OBPAdapter
      triggers: [casim.events.operational_events.WMSRun]
      conditions: []

    RORSP:
      state_adapter:
        _target_: casim.simulation_engine.state_adapter.ReORSPAdapter
      triggers: [casim.events.operational_events.TruckDisruption, casim.events.operational_events.VolumeShiftAcrossDay, casim.events.operational_events.OrderIngestion]
      conditions: []
