components:
  - casim.pipelines.problem_based_template.InstanceLoader
  - casim.pipelines.problem_based_template.OrdersProvider
  - casim.pipelines.subproblems.item_assingment.GreedyIA
  - casim.pipelines.subproblems.batching.FiFo
  - casim.pipelines.subproblems.picker_routing.TSPRouting
  - casim.pipelines.subproblems.scheduling.SPTScheduler
  - casim.pipelines.problem_based_template.ResultAggregationScheduling
